### ISSUE TITLE
Assignment 1 TODO List

### ISSUE THREAD

**Issue by elmartirta** [elmartirta/CISC282#1]
==STARTUP==

- [x] Find 2 Recipies
- [x] Create a "Hello world" for your website
- [x] Create a second "Hello Canada!" page for the second recipie

==REQUIREMENTS==
- [x] two html pages for each recipie
- [x] one CSS Stylesheet for both pages

==HTML==
- [x] HTML File for recipies one and two
- [x] Use correct tags
- [x] Recipie Header Section
- [x] Ingredients Section
- [x] Instructions Section
- [x] General Information Section
- [x]  - preparation time
- [x]  - cook time
- [x]  - # of servings

==CSS== 
- [x] at least 2 ID selectors
- [x] 1 class selector

==STYLE==
- [x]  webpage title == recipie
- [x] page heading contains recipie name
- [x] page heading contains chef's trademark 
- [x] Heading.size = 3em
- [x] Heading.color = #D80000
- [x] Foreground.color = white
- [x] Heading.position = center
- [x] All other headings underlined and bolded
- [x] All other headings aligned to the left
- [x] All headings other than h1 can have any color
- [x] body.font = Verdana or other sans serif font
- [x] body.color = black 
- [x] body.links.color = #000099
- [x] Abbreviations should have alt-text of full meaning
- [x] Lists should have a different color
- [x] ol and ul should have the same background
- [x] Ordered lists should have roman numerals
- [x] add a favicon
- [x] Each page should have a link to the other page's recipie
- [x] add a copyright notice
Copyright © 2017 CISC 282

                        All Rights Reserved
